### ISSUE TITLE
When postgresql_app_name is specified, user cannot log in

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-deploy-postgresql#5]
```
- name: create app database
  hosts: all
  roles:
    - role: gsa.datagov-deploy-postgresql
      vars:
        postgresql_app_name: inventory
        postgresql_role_password: secretpassword
      run_once: true
```

Play runs successfully, but `inventory` user cannot log in.
